provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  {{ if .GitHub }}
  system-github-event:
    lang: go
    handler: ./github-event
    image: functions/github-event:0.9.1
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      validate_hmac: true
      write_debug: true
      read_debug: true
      validate_customers: true
      customers_path: "{{.CustomersSecretPath}}"
    environment_file:
      - github.yml
      - gateway_config.yml
    secrets:
      - github-webhook-secret
      - payload-secret
      - customers

  github-push:
    lang: go
    handler: ./github-push
    image: functions/github-push:0.7.4
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      validate_hmac: true
      read_timeout: 10s
      write_timeout: 10s
      write_debug: true
      read_debug: true
    environment_file:
      - gateway_config.yml
      - github.yml
    secrets:
      - github-webhook-secret
      - payload-secret
    {{ end }}

  git-tar:
    lang: dockerfile
    handler: ./git-tar
    image: functions/of-git-tar:0.17.1
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      read_timeout: 15m
      write_timeout: 15m
      write_debug: true
      read_debug: true
    environment_file:
      - gateway_config.yml
      - github.yml
    secrets:
      - payload-secret
    {{ if .GitHub }}
      - private-key
    {{ end }}
# Uncomment this for GitLab
    {{ if not .GitHub }}
      - gitlab-api-token
    {{ end }}

  buildshiprun:
    lang: go
    handler: ./buildshiprun
    image: functions/of-buildshiprun:0.13.1
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      read_timeout: 5m
      write_timeout: 5m
      write_debug: true
      read_debug: true
      scaling_factor: 50
    environment_file:
      - buildshiprun_limits.yml
      - gateway_config.yml
      - github.yml
    secrets:
      - basic-auth-user
      - basic-auth-password
      - payload-secret
#      - swarm-pull-secret

  garbage-collect:
    lang: go
    handler: ./garbage-collect
    image: functions/garbage-collect:0.4.6
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      write_debug: true
      read_debug: true
      read_timeout: 30s
      write_timeout: 30s
    environment_file:
      - gateway_config.yml
    secrets:
      - basic-auth-user
      - basic-auth-password
      - payload-secret

  {{ if .GitHub }}
  github-status:
    lang: go
    handler: ./github-status
    image: functions/github-status:0.4.1
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      write_debug: true
      read_debug: true
      combine_output: false
      validate_hmac: true
      debug_token: true
    environment_file:
      - gateway_config.yml
      - github.yml
    secrets:
      - private-key
      - payload-secret
  {{ end }}

  import-secrets:
    lang: go
    handler: ./import-secrets
    image: functions/import-secrets:0.6.2
    annotations:
      com.openfaas.serviceaccount: sealedsecrets-importer-rw
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      write_debug: true
      read_debug: true
      validate_hmac: true
      combined_output: false
    environment_file:
      - github.yml
    secrets:
      - payload-secret

  pipeline-log:
    lang: go
    handler: ./pipeline-log
    image: functions/pipeline-log:0.3.5
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      write_debug: true
      read_debug: true
      combine_output: false
    environment_file:
      - gateway_config.yml
    secrets:
      - s3-access-key
      - s3-secret-key
      - payload-secret

  list-functions:
    lang: go
    handler: ./list-functions
    image: functions/list-functions:0.5.1
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      write_debug: true
      read_debug: true
    environment_file:
      - gateway_config.yml
    secrets:
      - basic-auth-user
      - basic-auth-password

  audit-event:
    lang: go
    handler: ./audit-event
    image: functions/audit-event:0.1.2
    labels:
      openfaas-cloud: "1"
      com.openfaas.scale.zero: false
    environment_file:
      - slack.yml

  echo:
    skip_build: true
    image: functions/alpine:latest
    labels:
      com.openfaas.scale.zero: false
    fprocess: cat
    environment:
      write_debug: true
      read_debug: true

  metrics:
    lang: go
    handler: ./system-metrics
    image: functions/system-metrics:0.2.0
    labels:
      com.openfaas.scale.zero: false
    environment_file:
      - gateway_config.yml
    environment:
      content_type: "application/json"

  function-logs:
    lang: go
    handler: ./function-logs
    image: functions/function-logs:0.2.0
    labels:
      openfaas-cloud: "1"
      role: openfaas-system
      com.openfaas.scale.zero: false
    environment:
      write_debug: true
      read_debug: true
    environment_file:
      - gateway_config.yml
    secrets:
      - basic-auth-user
      - basic-auth-password

