---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: auth-system-{{.RootDomain}}
  namespace: openfaas
spec:
  secretName: auth-system-{{.RootDomain}}-cert
  issuerRef:
    name: letsencrypt-{{.IssuerType}}
    kind: ClusterIssuer
  commonName: 'auth.system.{{.RootDomain}}'
  dnsNames:
  - 'auth.system.{{.RootDomain}}'
