apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: openfaas
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: "{{.Email}}"
    privateKeySecretRef:
      name: letsencrypt-staging
    dns01:
      providers:
      - name: {{.DNSService}}
        {{.DNSService}}:
          {{ if eq .DNSService "clouddns" }}
          serviceAccountSecretRef:
            name: "{{.DNSService}}-service-account"
            key: service-account.json
          project: "{{.ProjectID}}"
          {{else if eq .DNSService "route53" }}
          region: {{.Region}}
          # optional if ambient credentials are available; see ambient credentials documentation
          accessKeyID: {{.AccessKeyID}}
          secretAccessKeySecretRef:
            name: "{{.DNSService}}-credentials-secret"
            key: secret-access-key
          {{else if eq .DNSService "digitalocean" }}
            tokenSecretRef:
              name: digitalocean-dns
              key: access-token
          {{ end }}
